### ISSUE TITLE
ability to load more primitive files

### ISSUE THREAD

**Issue by btrepp** [mapeditor/rs-tiled#57] opened 2019-08-11 05:29 UTC
So I was playing integrating with amethyst, and wanted to just grab the map data without either a) having to integrate the tileset or b) provide the path on disk.

Looking at the source, it seems the data structure it wants to build is a Map, but maybe for integrating with other 'asset' loaders you could provide structures for MapFile and Tileset file, with mapfile containing either embedded tilesets or references to Tilesetfiles.
You should still be able to the maps from a combination of these structures.
I took this approach when I played around with tiled in purescript, and I liked the fact that the end user gets a bit more control on how to 'find' the files he needs.

Is there scope to add this to rs-tiled?. It might be a bit of a change?.

**Comment by alexdevteam** [comment] 2022-01-26 11:20
Duplicate of #37.

**Closed by alexdevteam** 2022-01-26 11:20 UTC
